const langObg = {
  "uz-UZ": {
    lang: "uz-UZ",
    type: "O'zbek",
    title: {
      name: "Samarqand davlat universiteti",
      table: "Darslar jadvali",
    },
    begin: "Boshlash",
    faculty: "Fakultetingizni tanlang",
    course: "Kursni tanlang",
    group: "Guruhingizni tanlang",
    schedule: "Dars jadvali",
    table: {
      start_time: "Kirish",
      end_time: "Chiqish",
      subject_name: "Fan nomi",
      auditorium: "Xona",
      trainingType: "Fan turi",
      employee: "O'qituvchi",
    },
    week: ["Dushanba", "Seshanba", "Chorshanba", "Payshanba", "Juma", "Shanba"],
    courseName: "kurs",
    notFound: "Kechirasiz bunday sahifa topilmadi!!!",
  },
  "en-US": {
    type: "English",
    lang: "en-US",
    title: {
      name: "Samarkand state university",
      table: "Lessons schedule",
    },
    begin: "Start",
    faculty: "Choose your faculty",
    course: "Choose your course",
    group: "Choose your group",
    schedule: "Lessons schedule",
    table: {
      start_time: "Enter",
      end_time: "Exit",
      subject_name: "Subject Name",
      auditorium: "Room",
      trainingType: "Type of subject",
      employee: "Teacher",
    },
    week: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    courseName: "course",
    notFound: "Sorry, no such page was found!!!",
  },
  "ru-RU": {
    type: "Русский",
    lang: "ru-RU",
    title: {
      name: "Самаркандский государственный университет",
      table: "Расписание уроков",
    },
    begin: "Начинать",
    faculty: "Выберите свой факультет",
    course: "Выбрать свою курс",
    group: "Выберите свою группу",
    schedule: "Расписание уроков",
    table: {
      start_time: "Введите",
      end_time: "Выход",
      subject_name: "Имя субъекта",
      auditorium: "Комната",
      trainingType: "Тип предмета",
      employee: "Учитель",
    },
    week: ["Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"],
    courseName: "курс",
    notFound: "Извините, такой страницы не найдено!!!",
  },
};
export default langObg;
